### ISSUE TITLE
Dataset URL disabled

### ISSUE THREAD

**Issue by surqing** [PhoebeGaoZhen/AttentionGRN#1]
https://zenodo.org/records/10720363

**Comment by PhoebeGaoZhen** [comment]
I'm sorry about that, we'll fix this as soon as possible.



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/11/2024 17:05 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [PhoebeGaoZhen/AttentionGRN] Dataset URL disabled (Issue #1) |

https://zenodo.org/records/10720363

**Comment by surqing** [comment]
Thanks
